name: Compile and Upload

# Controls when the action will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job that builds the latex file and uploads the result
  build_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Run default LaTeX to compile the document
      # Taken from https://github.com/marketplace/actions/latex-compilation
      - name: Compile Document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: demo.tex
          latexmk_use_lualatex: true # the action needs LuaLaTeX, my local machine can also handle pdfTeX
          args: -interaction=nonstopmode -shell-escape -latexoption=-file-line-error

      # Upload the resulting PDF
      - name: Upload Compiled Document
        uses: actions/upload-artifact@v2
        with:
          name: Demo
          path: demo.pdf
